/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui/keyboard/InputModal.hpp>
#include "BitmapDatabase.hpp"
#include <touchgfx/Color.hpp>
#include <texts/TextKeysAndLanguages.hpp>

InputModal::InputModal()
{
    setBackground(BitmapId(BITMAP_CONTROLS_BACKGROUND_ID), 0, 0);
    setShadeColor(touchgfx::Color::getColorFrom24BitRGB(0, 0, 0));
    //setShadeAlpha(125);

    keypad.setPosition(0, 133, 240, 187);
    add(keypad);

    boxInput.setPosition(0, 0, 240, 122);
    boxInput.setColor(touchgfx::Color::getColorFrom24BitRGB(247, 249, 250));
    add(boxInput);

    passwordEdit.setXY(73, 42);
    passwordEdit.setColor(touchgfx::Color::getColorFrom24BitRGB(0, 0, 0));
    passwordEdit.setLinespacing(0);
    passwordEdit.setTypedText(TypedText(T_PASSWORDEDIT));
    passwordEditBuffer[0] = 0;
    passwordEdit.setWildcard(passwordEditBuffer);
    add(passwordEdit);

    passwordHeadline.setXY(0, 22);
    passwordHeadline.setColor(touchgfx::Color::getColorFrom24BitRGB(0, 0, 0));
    passwordHeadline.setLinespacing(0);
    passwordHeadline.setTypedText(TypedText(T_PASSWORDHEADLINE));
    add(passwordHeadline);

    devicename.setXY(0, 0);
    devicename.setColor(touchgfx::Color::getColorFrom24BitRGB(0, 0, 0));
    devicename.setLinespacing(0);
    devicename.setTypedText(TypedText(T_CONNECTHEADLINE));
    devicenameBuffer[0] = 0;
    devicename.setWildcard(devicenameBuffer);
    add(devicename);

    buttonWithLabel1.setPosition(167, 78, 60, 44);
    buttonWithLabel1.setBitmaps(Bitmap(BITMAP_MODAL_BUTTON_ID), Bitmap(BITMAP_MODAL_BUTTON_PRESSED_ID));
    buttonWithLabel1.setLabelText(TypedText(T_BUTTONOK));
    buttonWithLabel1.setLabelColor(touchgfx::Color::getColorFrom24BitRGB(255, 255, 255));
    buttonWithLabel1.setLabelColorPressed(touchgfx::Color::getColorFrom24BitRGB(255, 255, 255));
    add(buttonWithLabel1);

    buttonWithLabel2.setPosition(13, 78, 60, 44);
    buttonWithLabel2.setBitmaps(Bitmap(BITMAP_MODAL_BUTTON_ID), Bitmap(BITMAP_MODAL_BUTTON_PRESSED_ID));
    buttonWithLabel2.setLabelText(TypedText(T_BUTTONCANCLE));
    buttonWithLabel2.setLabelColor(touchgfx::Color::getColorFrom24BitRGB(255, 255, 255));
    buttonWithLabel2.setLabelColorPressed(touchgfx::Color::getColorFrom24BitRGB(255, 255, 255));
    add(buttonWithLabel2);

    boxLine.setPosition(13, 67, 214, 2);
    boxLine.setColor(touchgfx::Color::getColorFrom24BitRGB(0, 171, 245));
    add(boxLine);
}
