/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef TIMEFORMAT_STYLE_HPP
#define TIMEFORMAT_STYLE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/timeanddate_screen/TimeAndDatePresenter.hpp>
#include <touchgfx/widgets/Image.hpp>
#include <touchgfx/widgets/TextAreaWithWildcard.hpp>
#include <touchgfx/containers/Container.hpp>
#include <touchgfx/widgets/TextArea.hpp>
#include <touchgfx/widgets/ToggleButton.hpp>
using namespace touchgfx;

class TimeFormatStyle : public Container
{
    public:
    TimeFormatStyle();
    virtual ~TimeFormatStyle();

    protected:
    //FrontendApplication& application()
    //{
    //    return *static_cast<FrontendApplication*>(Application::getInstance());
    //}

    /*
    * Member Declarations
    */
    //Container timeFormateContainer;
    Image background;
    TextArea timeFormat;
    TextAreaWithOneWildcard timeFomatExample;
    TextArea clockStyleText;
    ToggleButton timeFormattoggleBtn;
    ToggleButton clockStyletoggleBtn;

    /*
    * Wildcard Buffers
    */
    static const uint16_t TIMEFOMATEXAMPLE_SIZE = 30;
    touchgfx::Unicode::UnicodeChar timeFomatExampleBuffer[TIMEFOMATEXAMPLE_SIZE];

    private:

};

#endif // TIMEFORMAT_STYLE_HPP
